[package]
name = "ferrite-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ferrite-core.workspace = true

async-trait.workspace = true
chrono.workspace = true
rusqlite.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-rusqlite.workspace = true
tracing.workspace = true
