[package]
name = "ferrite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "ferrite"
path = "src/main.rs"

[dependencies]
ferrite-core.workspace = true
ferrite-storage.workspace = true

tokio.workspace = true
hickory-resolver.workspace = true
hickory-proto.workspace = true
tokio-rustls.workspace = true
webpki-roots.workspace = true
x509-parser.workspace = true
axum.workspace = true
hyper.workspace = true
hyper-util.workspace = true
tower-http.workspace = true
reqwest.workspace = true
fst.workspace = true
memmap2.workspace = true
psl.workspace = true
regex.workspace = true
rusqlite.workspace = true
tokio-rusqlite.workspace = true
mimalloc.workspace = true
libmimalloc-sys.workspace = true
dashmap.workspace = true
lru.workspace = true
arc-swap.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
postcard.workspace = true
chrono.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
anyhow.workspace = true
ring.workspace = true
argon2.workspace = true
subtle.workspace = true
socket2.workspace = true
sysinfo.workspace = true
dirs.workspace = true
flate2.workspace = true
tar.workspace = true
boringtun.workspace = true
smoltcp.workspace = true
async-trait.workspace = true
base64.workspace = true

[dev-dependencies]
tower.workspace = true
