use std::net::{Ipv4Addr, Ipv6Addr};
use std::str::FromStr;
use std::sync::Arc;

use bytes::Bytes;
use hickory_proto::op::{Message, OpCode, ResponseCode};
use hickory_proto::rr::rdata::{A, AAAA, CNAME};
use hickory_proto::rr::{Name, RData, Record, RecordType};
use hickory_proto::serialize::binary::BinEncodable;
use parking_lot::RwLock;

use crate::config::CustomRecordConfig;
use crate::dns::types::DnsResponse;
use crate::error::{FeriteError, Result};

/// One parsed custom DNS record stored in memory.
#[derive(Debug, Clone)]
pub struct CustomRecord {
    /// Normalised domain pattern (lowercase, no trailing dot).
    pub domain: String,
    /// Whether the pattern is a wildcard (`*.example.com`).
    pub is_wildcard: bool,
    /// The DNS suffix that must match for wildcards, e.g. `.example.com`.
    pub wildcard_suffix: String,
    pub record_type: RecordType,
    pub rdata: RData,
    pub ttl: u32,
}

/// Thread-safe store of custom DNS records.
pub struct CustomRecords {
    records: RwLock<Vec<CustomRecord>>,
    builtin_records: RwLock<Vec<CustomRecord>>,
}

impl CustomRecords {
    pub fn new() -> Arc<Self> {
        Arc::new(Self {
            records: RwLock::new(Vec::new()),
            builtin_records: RwLock::new(Vec::new()),
        })
    }

    /// Load initial records from config.
    pub fn load_from_config(&self, cfgs: &[CustomRecordConfig]) {
        let mut records = self.records.write();
        for cfg in cfgs {
            match parse_record(cfg) {
                Ok(r) => records.push(r),
                Err(e) => tracing::warn!("invalid custom record {:?}: {}", cfg.domain, e),
            }
        }
    }

    /// Load records generated by ferrite itself. These are hidden from the
    /// custom-records API but still take part in DNS lookup.
    pub fn load_builtin(&self, cfgs: &[CustomRecordConfig]) {
        let mut records = self.builtin_records.write();
        records.clear();
        for cfg in cfgs {
            match parse_record(cfg) {
                Ok(r) => records.push(r),
                Err(e) => tracing::warn!("invalid built-in record {:?}: {}", cfg.domain, e),
            }
        }
    }

    /// Add a record at runtime.
    pub fn add(&self, cfg: &CustomRecordConfig) -> Result<()> {
        let record = parse_record(cfg)?;
        let mut records = self.records.write();
        // Replace if same domain+type already exists.
        records.retain(|r| !(r.domain == record.domain && r.record_type == record.record_type));
        records.push(record);
        Ok(())
    }

    /// Remove all records for `domain`.
    pub fn remove(&self, domain: &str) -> bool {
        let domain = normalise(domain);
        let mut records = self.records.write();
        let before = records.len();
        records.retain(|r| r.domain != domain);
        records.len() < before
    }

    /// List all records.
    pub fn list(&self) -> Vec<CustomRecordConfig> {
        self.records
            .read()
            .iter()
            .map(|r| CustomRecordConfig {
                domain: r.domain.clone(),
                record_type: format!("{}", r.record_type),
                value: rdata_to_string(&r.rdata),
                ttl: r.ttl,
            })
            .collect()
    }

    /// Look up a domain + qtype and return a ready-to-send DNS response, or `None`.
    pub fn lookup(&self, query: &Message, name: &str, qtype: u16) -> Option<DnsResponse> {
        let name_norm = normalise(name);
        let want_type = RecordType::from(qtype);

        let records = self.records.read();
        if let Some(record) = find_record(&records, &name_norm, want_type) {
            return build_response(query, name, record);
        }

        let builtin_records = self.builtin_records.read();
        let record = find_record(&builtin_records, &name_norm, want_type)?;

        build_response(query, name, record)
    }
}

// ── Parsing ───────────────────────────────────────────────────────────────────

fn parse_record(cfg: &CustomRecordConfig) -> Result<CustomRecord> {
    let domain = normalise(&cfg.domain);

    let (is_wildcard, wildcard_suffix) = if let Some(rest) = domain.strip_prefix("*.") {
        (true, format!(".{}", rest))
    } else {
        (false, String::new())
    };

    let record_type = match cfg.record_type.to_uppercase().as_str() {
        "A" => RecordType::A,
        "AAAA" => RecordType::AAAA,
        "CNAME" => RecordType::CNAME,
        other => {
            return Err(FeriteError::Config(format!(
                "unsupported record type '{}'",
                other
            )))
        }
    };

    let rdata = match record_type {
        RecordType::A => {
            let ip = Ipv4Addr::from_str(&cfg.value).map_err(|_| {
                FeriteError::Config(format!("invalid IPv4 '{}' for A record", cfg.value))
            })?;
            RData::A(A(ip))
        }
        RecordType::AAAA => {
            let ip = Ipv6Addr::from_str(&cfg.value).map_err(|_| {
                FeriteError::Config(format!("invalid IPv6 '{}' for AAAA record", cfg.value))
            })?;
            RData::AAAA(AAAA(ip))
        }
        RecordType::CNAME => {
            let target = Name::from_str(&cfg.value).map_err(|_| {
                FeriteError::Config(format!("invalid CNAME target '{}'", cfg.value))
            })?;
            RData::CNAME(CNAME(target))
        }
        _ => unreachable!(),
    };

    Ok(CustomRecord {
        domain,
        is_wildcard,
        wildcard_suffix,
        record_type,
        rdata,
        ttl: cfg.ttl,
    })
}

fn find_record<'a>(
    records: &'a [CustomRecord],
    name_norm: &str,
    want_type: RecordType,
) -> Option<&'a CustomRecord> {
    let name_match = |r: &CustomRecord| {
        if r.is_wildcard {
            name_norm.ends_with(&r.wildcard_suffix) && name_norm != r.domain
        } else {
            name_norm == r.domain
        }
    };

    // Prefer an exact qtype match (or any record for ANY queries).
    if let Some(exact) = records
        .iter()
        .find(|r| name_match(r) && (r.record_type == want_type || want_type == RecordType::ANY))
    {
        return Some(exact);
    }

    // Fall back to a CNAME only when no direct record of the queried type
    // exists, so an A/AAAA query isn't answered with a bare CNAME (cached under
    // the A/AAAA key) when a real address record was configured.
    if want_type != RecordType::CNAME {
        return records
            .iter()
            .find(|r| name_match(r) && r.record_type == RecordType::CNAME);
    }
    None
}

// ── Response building ─────────────────────────────────────────────────────────

fn build_response(query: &Message, name: &str, record: &CustomRecord) -> Option<DnsResponse> {
    let fqdn = if name.ends_with('.') {
        name.to_string()
    } else {
        format!("{}.", name)
    };

    let rr_name = Name::from_str(&fqdn).ok()?;
    let rr = Record::from_rdata(rr_name, record.ttl, record.rdata.clone());

    let mut resp = Message::response(query.metadata.id, OpCode::Query);
    resp.metadata.authoritative = true;
    resp.metadata.recursion_desired = query.metadata.recursion_desired;
    resp.metadata.recursion_available = true;
    resp.metadata.response_code = ResponseCode::NoError;
    resp.add_queries(query.queries.iter().cloned());
    resp.add_answer(rr);

    let bytes = resp.to_bytes().ok()?;
    Some(DnsResponse {
        bytes: Bytes::from(bytes),
        ttl: record.ttl,
    })
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn normalise(domain: &str) -> String {
    domain
        .to_ascii_lowercase()
        .trim_end_matches('.')
        .to_string()
}

fn rdata_to_string(rdata: &RData) -> String {
    match rdata {
        RData::A(a) => a.0.to_string(),
        RData::AAAA(a) => a.0.to_string(),
        RData::CNAME(c) => c.0.to_string(),
        other => format!("{:?}", other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hickory_proto::op::Query;
    use hickory_proto::serialize::binary::BinDecodable;

    fn cfg(domain: &str, record_type: &str, value: &str) -> CustomRecordConfig {
        CustomRecordConfig {
            domain: domain.to_string(),
            record_type: record_type.to_string(),
            value: value.to_string(),
            ttl: 60,
        }
    }

    fn query(name: &str, record_type: RecordType) -> Message {
        let mut msg = Message::new(0, hickory_proto::op::MessageType::Query, OpCode::Query);
        let name = Name::from_str(&format!("{}.", name)).unwrap();
        msg.add_query(Query::query(name, record_type));
        msg
    }

    fn answer_a(resp: &DnsResponse) -> Ipv4Addr {
        let msg = Message::from_bytes(&resp.bytes).unwrap();
        match &msg.answers[0].data {
            RData::A(ip) => ip.0,
            other => panic!("expected A answer, got {:?}", other),
        }
    }

    #[test]
    fn builtin_records_are_hidden_from_custom_record_list() {
        let records = CustomRecords::new();
        records.load_builtin(&[cfg("fe.te", "A", "192.168.1.10")]);

        assert!(records.list().is_empty());

        let resp = records.lookup(&query("fe.te", RecordType::A), "fe.te", 1);
        assert_eq!(
            resp.map(|r| answer_a(&r)),
            Some("192.168.1.10".parse().unwrap())
        );
    }

    fn answer_type(resp: &DnsResponse) -> RecordType {
        let msg = Message::from_bytes(&resp.bytes).unwrap();
        msg.answers[0].record_type()
    }

    #[test]
    fn a_query_prefers_direct_a_record_over_cname() {
        let records = CustomRecords::new();
        records
            .add(&cfg("host.test", "CNAME", "target.test"))
            .unwrap();
        records.add(&cfg("host.test", "A", "192.168.1.5")).unwrap();

        // With both a CNAME and a direct A, an A query must get the A record,
        // not the bare CNAME (which would be cached under the A key).
        let resp = records
            .lookup(&query("host.test", RecordType::A), "host.test", 1)
            .unwrap();
        assert_eq!(answer_type(&resp), RecordType::A);
        assert_eq!(answer_a(&resp), "192.168.1.5".parse::<Ipv4Addr>().unwrap());
    }

    #[test]
    fn a_query_falls_back_to_cname_when_no_direct_record() {
        let records = CustomRecords::new();
        records
            .add(&cfg("cn.test", "CNAME", "target.test"))
            .unwrap();

        // No direct A — the CNAME is a legitimate fallback for the chain.
        let resp = records
            .lookup(&query("cn.test", RecordType::A), "cn.test", 1)
            .unwrap();
        assert_eq!(answer_type(&resp), RecordType::CNAME);
    }

    #[test]
    fn custom_record_overrides_builtin_record() {
        let records = CustomRecords::new();
        records.load_builtin(&[cfg("fe.te", "A", "192.168.1.10")]);
        records.add(&cfg("fe.te", "A", "192.168.1.20")).unwrap();

        let resp = records.lookup(&query("fe.te", RecordType::A), "fe.te", 1);
        assert_eq!(
            resp.map(|r| answer_a(&r)),
            Some("192.168.1.20".parse().unwrap())
        );
    }
}
